### ISSUE TITLE
Permissions issue after plugin install

### ISSUE THREAD

**Issue by paul-hammant** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#12]
```
    The user webdav is missing execute permissions on this directory.
    The user webdav is missing read permissions on this directory.
    The user webdav is missing write permissions on this directory.
```

**Comment by ryecoaaron** [comment]
Did you try fixing what it is telling you is wrong?  In the shared folder tab, the privileges button will let you give the webdav user those permissions.  If you created it with too restrictive of permissions, then the resetperms plugin will help you reset it.

**Comment by paul-hammant** [comment]
I've no command line access (for other reasons the SSH-in-the-DOM plugin doesn't complete its install). So I'm saying all I have is the web interface.  There's no WebDAV user in shared folders to click then privileges button for.  The install of the WebDav plugin doesn't auto add the users it needs?

**Comment by ryecoaaron** [comment]
I was remembering how to configure that plugin incorrectly.  You actually just need to add at least one user to the webdav-users group (can be done from the web interface) and you that user needs permissions to the shared folder configured in the plugin (can also be done from the web interface).  So, no reason to use the command line.

If you do need command line access, you can use putty to connect to the system.

**Comment by paul-hammant** [comment]
I'm on a Mac, and SSHD isn't on by default for the OMV install onto an Odroid-C1.

I've added a `webdav-users` group by hand because it wasn't created during the webdav-plugin installation. After that, clicking on the 'paul' user then going to edit groups for that, I can't see  webdav-users listed as a group at all. Discouraging.

**Comment by ryecoaaron** [comment]
It does create the webdav-users group - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav/blob/master/debian/postinst#L11 - but it is a system group and will only be visible in the OMV web interface where you select groups for a user.  I don't know why it wasn't created on your system.

sshd should be enable (but root login disabled) for all arm images.  Even if it is disabled, you can enable it in the web interface.

Not sure why being on a mac changes anything.
