### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by zoeeer** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#13]
Thanks for the plugin! It cost me great effort trying to build a WebDAV service myself.

However, I hope this plugin can be improved regarding security and permissions:
1. It will be good if I can serve WebDAV through a seperate port (#8 )
2. The plugin allows admin user login through WebDAV, even if it's not in the 'webdav-users' group. I'd really like to turn this feature off.
3. Once a user logs in, he/she will be assigned the permissions of the 'webdav' user. Is it possible to maintain the login user's own ACL permissions?

**Comment by ryecoaaron** [comment]
This plugin probably won't see any more changes in favor of using docker - https://forum.openmediavault.org/index.php/Thread/24545-Why-should-you-use-or-not-use-dockers/?postID=186122#post186122

**Comment by zoeeer** [comment]
Thanks for replying.

I see the list of plugins in the link you provided. I don't quite understand it though -- if a plugin is marked 'docker', will it be installed via docker and run as a container? Does it make any difference regarding the security questions I had?

Can I try the docker version of WebDAV for my OMV 4.x?

**Comment by ryecoaaron** [comment]
If the list says docker, then there will be no plugin.  You install the docker plugin (openmediavault-docker-gui) and then find the webdav docker image of your choice.  And yes, this is possible on OMV 4.x.  Here are some helpful videos on how to use the docker plugin - https://forum.openmediavault.org/index.php/Thread/23005-Installation-and-Setup-Videos-Beginning-Intermediate-and-Advanced/

**Comment by zoeeer** [comment]
Thanks for the guide. The docker plugin seems easy enough to use!

I've searched for a WebDAV docker image, but none of them seem to meet my needs though. Basically I want a WebDAV server that can support multiuser login and give them the correct permissions according to a shared folder's ACL. I've used the WebDAV plugin for Synology NAS so I think it is possible technically. However I haven't found such a docker image nor tutorial to set it up. I really appreciate if you have any ideas on this.

**Comment by ryecoaaron** [comment]
Unfortunately, I don't use webdav and hate ACLs,  So, I wouldn't be a good one for this.  This image - https://hub.docker.com/r/bytemark/webdav/ - supports multiple users and I would guess ACLs would just be supported because it is a filesystem feature.

**Comment by zoeeer** [comment]
I saw this image before my last comment. It says "It can only be accessed with a single username and password" at the beginning of the usage guide, so I turned to other options immediately. Now I've read all the instructions, I think it's worth trying.
I'm sorry for not reading things thoroughly. Thanks for your help!
