### ISSUE TITLE
WebDAV endpoint per shared folder

### ISSUE THREAD

**Issue by viharm** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#15]
My use case requires a different set of shares to be synced with my personal mobile, work mobile, home PC and work PC. Since my work PC is behind a restrictive firewall, I believe WebDAV is a good option to access my OMV shares (as it uses HTTP or HTTPS).

I tried this plugin, but it only allows a WebDAV endpoint for one share from OMV. Is it possible to expose multiple shares, each with their individual endpoint?

**Comment by ryecoaaron** [comment]
It is not possible with the plugin and the plugin is not maintained any longer.  I recommend looking at webdev docker images.
