### ISSUE TITLE
OMV 6

### ISSUE THREAD

**Issue by To0wnn** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#16]
Hi,

Can not find this plugin in OMV 6?
Any reason?

Kindregards,

Tony

**Comment by ryecoaaron** [comment]
It isn’t done yet and I have been on vacation.

**Comment by Stoly1974** [comment]
Hi, 
Unfortunately I still can't find the plugin in the OMV 6.
Please can you help?

best regards
Stoly

**Comment by ryecoaaron** [comment]
Still not ready.

**Comment by ryecoaaron** [comment]
Plugin is in the testing repo.
