### ISSUE TITLE
Consider using WebDAV-Daemon by leveraging Nginx' reverse proxy feature

### ISSUE THREAD

**Issue by davidebeatrici** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#18]
[WebDAV-Daemon](https://github.com/couling/WebDAV-Daemon) strictly relies on PAM to access files and folders, matching OpenMediaVault's behavior for the protocols that are officially supported (with Samba being the most used, for better or worse).

By making the service listen on an arbitrary port (as long as it's not 80 or 443), we can tell Nginx to redirect any requests to it and deliver the responses to the client (reverse proxy): https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy

**Comment by ryecoaaron** [comment]
It does look interesting but it doesn't look like WebDAV-daemon is actively maintained anymore and I would have to maintain packaging since it isn't in the Debian repos.
