### ISSUE TITLE
HTTP status code for non-existent paths is 302 instead of 404

### ISSUE THREAD

**Issue by xmcp** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#21]
Currently some clients like [Zotero](https://www.zotero.org/support/sync#webdav) cannot connect to OMV WebDAV, reporting an error `Your WebDAV server is claiming that a nonexistent file exists`:

![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav/assets/6646473/c1e3e099-ee98-4352-a01c-5bf5f7c18cff)

We can confirm that OMV indeed responds with 302 for an non-existent path in access log:

```
IP - username [13/Mar/2024:03:22:40 +0800] "GET /webdav/zotero/nonexistent.prop HTTP/1.1" 302 138 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0"
IP - - [13/Mar/2024:03:22:41 +0800] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

This is because the main site configuration (`/etc/nginx/sites-enabled/openmediavault-webgui`) redirects all 404 pages to homepage:

```
error_page 404 = $scheme://$host:$server_port/#/404;
```

This plugin should override the above `error_page` directive in the webdav location to avoid this behavior. I will open a PR for this.

**Comment by ryecoaaron** [comment]
7.0.2 is in the repo now.
