### ISSUE TITLE
Directory operations not working for many clients that omit the trailing slash

### ISSUE THREAD

**Issue by xmcp** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#23]
Many WebDAV clients (including Windows Explorer, Finder, and [Documents for iOS](https://apps.apple.com/us/app/documents-file-manager-vpn/id364901807)) are incompatible of nginx WebDAV because they will omit the trailing slash (`METHOD /path/to/dir HTTP/1.1` instead of `METHOD /path/to/dir/ HTTP/1.1`) for directory operations.

For example, Windows Explorer can't create a directory, resulting in HTTP 409:

```
// access.log
127.0.0.1 - username [24/Mar/2024:01:12:08 +0800] "MKCOL /webdav/example HTTP/1.1" 409 144 "-" "Microsoft-WebDAV-MiniRedir/10.0.19045"
// error.log
2024/03/24 01:12:08 [error] 2026468#2026468: *18455 MKCOL can create a collection only, client: 127.0.0.1, server: openmediavault-webgui, request: "MKCOL /webdav/example HTTP/1.1", host: "hostname"
```

Similarly it can't delete a directory:

```
// access.log
127.0.0.1 - username [24/Mar/2024:01:13:56 +0800] "DELETE /webdav/example HTTP/1.1" 409 144 "-" "Microsoft-WebDAV-MiniRedir/10.0.19045"
// error.log
2024/03/24 01:13:56 [error] 2026470#2026470: *18496 DELETE "/path/to/example" failed (21: Is a directory), client: 127.0.0.1, server: openmediavault-webgui, request: "DELETE /webdav/example HTTP/1.1", host: "hostname"
```

Or rename a directory:

```
// access.log
127.0.0.1 - username [24/Mar/2024:01:15:31 +0800] "MOVE /webdav/example HTTP/1.1" 400 150 "-" "Microsoft-WebDAV-MiniRedir/10.0.19045"
// error.log
2024/03/24 01:15:31 [error] 2026469#2026469: *18536 "/webdav/example" is collection, client: 127.0.0.1, server: openmediavault-webgui, request: "MOVE /webdav/example HTTP/1.1", host: "hostname"
```

I found [a blog post](https://www.robpeck.com/2020/06/making-webdav-actually-work-on-nginx/) that fixes nginx WebDAV for such clients by rewriting the problematic URLs and headers.

I can try to figure out a pull request for this issue based on the above blog post, but the conf file will be much longer and may bring other corner case issues. Switching to another WebDAV server may be a better choice.

**Comment by ryecoaaron** [comment]
I'm not against using a different server but that would almost certainly mean using a different port.

I do see the two packages from the article are new enough now.

**Comment by ryecoaaron** [comment]
The plugin is already install libnginx-mod-http-dav-ext.  So, dav_ext_methods could be updated as well.

**Comment by ryecoaaron** [comment]
code changes to help:

```
            dav_ext_methods PROPFIND OPTIONS LOCK UNLOCK;
            dav_ext_lock zone=foo;
            create_full_put_path on;
```

```
# The configuration was based on: https://nworm.icu/post/nginx-webdav-dolphin-deken/
# if the request method is MKCOL or is to a directory, add / at the end of the request if it was missing 
if ($request_method = MKCOL) {
    rewrite ^(.*[^/])$ $1/ break; 
}
if (-d $request_filename) { 
    rewrite ^(.*[^/])$ $1/ break; 
}

# if the request method is copy or move a directory, add / at the end of the request if it was missing
set $is_copy_or_move 0;
set $is_dir 0;
if (-d $request_filename) { 
    set $is_dir 1; 
}
if ($request_method = COPY) {
    set $is_copy_or_move 1;
}
if ($request_method = MOVE) {
    set $is_copy_or_move 1;
}
set $is_rewrite "${is_dir}${is_copy_or_move}";
if ($is_rewrite = 11) {
    rewrite ^(.*[^/])$ $1/ break;
}
```

**Comment by ryecoaaron** [comment]
I didn't test it but how does this change look?
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav/commit/5354499da4db9d725423a6a5a71887d8b0d400fb

**Comment by xmcp** [comment]
Rewriting the URL is not enough. For directory MOVE and COPY, the destination path is set in the `Destination:` HTTP header. Refer to the `client sent invalid "Destination" header` error log above. The blog I mentioned used `more_set_input_headers` to rewrite that.

Btw how do I temporarily apply and test that change? I'm not very familiar with the configuration system of OMV.

**Comment by ryecoaaron** [comment]
> Rewriting the URL is not enough. For directory MOVE and COPY, the destination path is set in the Destination: HTTP header. Refer to the client sent invalid "Destination" header error log above. The blog I mentioned used more_set_input_headers to rewrite that.

I was trying to use all three blogs/wiki that I added the url to in the code.  I guess I didn't do a very good job consolidated.  I also thought maybe the arch linux code was more up to date.  I guess not.  Feel free to fix whatever is broken.

> Btw how do I temporarily apply and test that change? I'm not very familiar with the configuration system of OMV.

Edit /srv/salt/omv/deploy/webdav/default.sls and then run the following to update the saltstack cache:

sudo /usr/bin/salt-call --local saltutil.clear_cache
sudo omv-salt stage run prepare

Then the following to run your changes:

sudo omv-salt deploy run webdav

**Comment by xmcp** [comment]
I will share my configuration that seems to work across all of my WebDAV clients in a PR.

Note that we need to install the `libnginx-mod-http-headers-more-filter` package. What is the correct way of adding such a dependency? Is adding its name in the [debian/control](https://github.com/xmcp/openmediavault-webdav/blob/master/debian/control#L11) file enough?

**Comment by ryecoaaron** [comment]
Yes, debian/control is where that dependency should be added.
