### ISSUE TITLE
when i set extra options in webdav plugins it not working.

### ISSUE THREAD

**Issue by wanglvhang** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#27]
after i add configuration " client_max_body_size 100m; " in omv webdev plugin
![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav/assets/936437/0b635aaf-612f-49ae-8b7d-255a6383a60e)

when i upload file that not bigger than 100m, it  throws error:
`2024/04/23 16:38:29 [error] 144406#144406: *15 client intended to send too large body: 95322756 bytes, client: xxxxxxxxxxx, server: openmediavault-webgui, request: "PUT /webdav/phone_backup/VID_20231104_171346.mp4 HTTP/2.0", host: "xxxxxxxxxxxx"`

i'm using  OMV 7.0.5-1 (Sandworm)
and webdav plugin:  openmediavault-webdav 7.0.3

**Comment by ryecoaaron** [comment]
I guess I missed actually adding extra options to the config file.  I will add it.

**Comment by ryecoaaron** [comment]
It took longer to test the change than make the change : )
