### ISSUE TITLE
Show WebDAV in Services in Dashboard

### ISSUE THREAD

**Issue by LnLcFlx** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#29]
Show WebDAV alongside NFS, Rszync etc. in the Dashboard.

**Comment by ryecoaaron** [comment]
It would only show whether webdav is enabled or not.  Since webdav is just using an nginx module under OMV's instance of nginx, the omv web interface working tells you webdav is running if enabled.

**Comment by ryecoaaron** [comment]
Available on 7.0.5 in the repo now.
