### ISSUE TITLE
How to set permissions

### ISSUE THREAD

**Issue by yduanBioinfo** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#32]
I have installed webdav services, and it works perfect for one user.
However, I want to share it to more than one user, and every one has it's own directory.
I tried to create multiple  webdav services, and it is definitely not working.
And I try to set permissions for subdirectory, like setfacl command. However, it seems that all files is accessed by user named "www-data", the permission controls failed.

**Comment by ryecoaaron** [comment]
Your use case is more advanced than the plugin supports.  The plugin uses nginx's webdav module which does not support ACLs either.  You might want to look at running nextcloud or some other webdav server (maybe sabredav) in a container.
