### ISSUE TITLE
Blank page display (omv 3.0)

### ISSUE THREAD

**Issue by subzero79** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#5]
Using the latest package available in bintray, after enabling webdav the web page just displays blank there are no errors in nginx logs and console.
Looking at the commits in github the mkconf looks different from the current one in the package, once upgraded through dev plugin, now the web page prompts for login, but after entering credentials it times out.

The dev console gives this error

```Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError```

The nginx log now this time shows the exception

http://hastebin.com/jusesuvota.tex

**Comment by nohatssir** [comment]
This should be fixed with 9a5a0136331148b236aef3bbad28aa8e786b1c72.

**Comment by subzero79** [comment]
Works as expected now. I didn't want to open another thread but I think it would be good to add an info text note for the following.

- For users to be able to upload files the share folder needs write permissions for the webdav user
- For getting login access users must be member of webdav-users group

**Comment by nohatssir** [comment]
It should only be necessary to have read-write rights for webdav-users. However, I'm thinking of a solution that will warn for incorrect permissions with a sharedfoldercombo. I just need to get time/motivation for it and see if it's a feasible solution.
