### ISSUE TITLE
localization - untranslatable strings

### ISSUE THREAD

**Issue by p-bo** [OpenMediaVault-Plugin-Developers/openmediavault-webdav#7]
Strings:

**Only users that are members of the 'webdav-users' group will be permitted to use WebDAV.**

**Make sure the user 'webdav' has read and write access to the shared folder.**

...are hardcoded and not sourced from localization files, where are missing too.

**Comment by ryecoaaron** [comment]
The translatable strings are using single quotes right now and xgettext doesn't detect them.  I am looking for a solution.

**Comment by p-bo** [comment]
Thanks for explanation and looking for solution. Will gladly contribute with translation into Czech when it will be ready.

**Comment by p-bo** [comment]
It seems to be solved in commit 38c71ea687299c485aa0a7b607b9b7d30cf0456f - thanks a lot :)
